version: "3.4"

services:
  trh-op-bridge-app:
    image: trh-op-bridge-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
